### ISSUE TITLE
1.6.0 tag has 1.6.0-rc.2 as enum value

### ISSUE THREAD

**Issue by frankinspace** [podaac/cloud-notification-message-schema#35]
The "version" property in the 1.6.0 tag has an rc value for one of the enums:

https://github.com/podaac/cloud-notification-message-schema/blob/v1.6.0/cumulus_sns_schema.json#L94

It seems this was fixed on `master` but not in the tag.

**Comment by skorper** [comment]
Thanks @frankinspace ! I manually fixed this issue. 

@cbanh, is looks like the tag is being created in the GH action before the version in the schema is updated
